# Generated by Django 4.2.1 on 2023-05-04 10:15

from django.db import migrations


def create_data(apps, schema_editor):
    Record = apps.get_model('table', 'Record')
    Record(date="2023-05-04", name="John",quantity=3, distance=220).save()
    Record(date="2023-05-04", name="Nick",quantity=5, distance=230).save()
    Record(date="2023-05-04", name="Bill",quantity=2, distance=10).save()
    Record(date="2023-05-04", name="Ilon",quantity=8, distance=820).save()


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
